from pydantic import BaseModel, Field
from typing import Literal, Optional, List
from enum import Enum


class Message(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(
        ...,
        description="Role of the message sender in the conversation."
    )
    content: str = Field(
        ...,
        description="Text content of the message."
    )


class CodeContext(BaseModel):
    code: Optional[str] = Field(
        default=None,
        description="Extracted code snippet from the user prompt."
    )
    task: Optional[str] = Field(
        default=None,
        description="Extracted the task that the user wants to do."
    )


class RetrievalContext(BaseModel):
    """Context retrieved from the user's own uploaded project files."""
    documents: List[str] = Field(
        default_factory=list,
        description="Relevant chunks retrieved from the user's project vector DB."
    )


class CodebaseContext(BaseModel):
    """Context retrieved from the shared curated GitHub codebase DB."""
    documents: List[str] = Field(
        default_factory=list,
        description="Relevant chunks retrieved from the curated codebase reference DB."
    )


class ToolResult(BaseModel):
    output: Optional[str] = Field(
        default=None,
        description="Output generated by the executed tool or LLM."
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message returned if the tool execution failed."
    )


class IntentType(str, Enum):
    GENERATE     = "generate_code"
    AUTOCOMPLETE = "autocomplete"
    EXPLAIN      = "explain_code"
    BUG_DETECT   = "bug_detection"
    REFACTOR     = "refactor"


class Intent(BaseModel):
    type: Literal[
        "generate_code",
        "autocomplete",
        "explain_code",
        "bug_detection",
        "refactor"
    ]


class CodeGenerationResult(BaseModel):
    code: str = Field(..., description="Generated code that solves the user's task.")
    explanation: Optional[str] = Field(default=None, description="Short explanation of the generated code.")


class CodeExplanationResult(BaseModel):
    explanation: str = Field(..., description="Detailed explanation of the provided code.")
    key_points: Optional[List[str]] = Field(default=None, description="Important concepts used in the code.")


class BugDetectionResult(BaseModel):
    bugs: List[str] = Field(..., description="List of detected bugs or issues.")
    fixed_code: Optional[str] = Field(default=None, description="Corrected version of the code.")
    suggestions: Optional[List[str]] = Field(default=None, description="Additional improvements or best practices.")


class AutocompleteResult(BaseModel):
    completion: str = Field(..., description="Only the newly generated continuation of the code.")
    full_code: str = Field(..., description="The complete code after applying the completion.")


class CodeAuditResult(BaseModel):
    vulnerabilities: Optional[List[str]] = Field(default=None, description="List of security issues detected.")
    severity: Optional[List[str]] = Field(default=None, description="Severity per vulnerability: low, medium, high.")
    fixed_code: Optional[str] = Field(default=None, description="Safer version of the code.")
    suggestions: Optional[List[str]] = Field(default=None, description="Additional security recommendations.")


class CodeRefinementResult(BaseModel):
    refined_code: str = Field(..., description="The updated code with added docstrings and comments.")
    changes: Optional[List[str]] = Field(default=None, description="List of changes applied.")


class FileEntry(BaseModel):
    """A single file the LLM decided to produce from the refined code."""
    file_name: str = Field(..., description="Snake_case filename with .py extension, e.g. 'auth_router.py'.")
    content:   str = Field(..., description="Complete file content — never truncated.")


class FileSplitResult(BaseModel):
    """
    The LLM's decision on how to split (or not split) the refined code into files.
    Always contains at least one FileEntry.
    """
    files: List[FileEntry] = Field(
        ...,
        description="One or more files to write. Single-file results have exactly one entry.",
    )


class OutputFile(BaseModel):
    """A file that was actually written to disk by the file_writer_node."""
    file_name: str = Field(..., description="Filename as written.")
    file_path: str = Field(..., description="Absolute or relative path on disk.")
    content:   str = Field(..., description="The content written to the file.")


class AgentState(BaseModel):

    user_input: str = Field(..., description="The raw prompt provided by the user.")

    project_id: Optional[str] = Field(
        default=None,
        description="The project ID used to scope vector DB retrieval to the user's own files."
    )

    intent: Optional[IntentType] = Field(
        default=None,
        description="Detected intent of the user request."
    )

    messages: List[Message] = Field(
        default_factory=list,
        description="Conversation history between the user and the assistant."
    )

    code_context: CodeContext = Field(
        default_factory=CodeContext,
        description="Structured code and task extracted from the user prompt."
    )

    # ── RAG Context (split into two clear sources) ──────────────────

    retrieval_context: RetrievalContext = Field(
        default_factory=RetrievalContext,
        description="Context retrieved from the user's own uploaded project files."
    )

    codebase_context: CodebaseContext = Field(
        default_factory=CodebaseContext,
        description="Context retrieved from the shared curated GitHub codebase DB."
    )

    # ── Outputs ─────────────────────────────────────────────────────

    result: Optional[str] = Field(
        default=None,
        description="Final response generated by the assistant."
    )

    last_code: Optional[str] = Field(
        default=None,
        description="Last generated or processed code snippet."
    )

    task: Optional[str] = None

    audit_context: Optional[CodeAuditResult] = Field(
        default=None,
        description="Structured audit results from the code guard node."
    )

    audit_history: Optional[List[CodeAuditResult]] = Field(
        default_factory=list,
        description="History of all audit results for this session."
    )

    output_files: List[OutputFile] = Field(
        default_factory=list,
        description="Files written to disk by the file_writer_node.",
    )
