from pydantic import BaseModel, Field
from typing import Literal, Optional, List
from enum import Enum


class Message(BaseModel):
    role: Literal["user", "assistant", "system"] = Field(
        ...,
        description="Role of the message sender in the conversation."
    )
    content: str = Field(
        ...,
        description="Text content of the message."
    )


class CodeContext(BaseModel):
    code: Optional[str] = Field(
        default=None,
        description="Extracted code snippet from the user prompt."
    )
    
    task: Optional[str] = Field(
        default=None,
        description="Extracted the task that the user want to do."
    )




class RetrievalContext(BaseModel):
    documents: List[str] = Field(
        default_factory=list,
        description="Relevant documents or code snippets retrieved from the vector database or project files."
    )


class ToolResult(BaseModel):
    output: Optional[str] = Field(
        default=None,
        description="Output generated by the executed tool or LLM."
    )

    error: Optional[str] = Field(
        default=None,
        description="Error message returned if the tool execution failed."
    )


class IntentType(str, Enum):
    GENERATE = "generate_code"
    AUTOCOMPLETE = "autocomplete"
    EXPLAIN = "explain_code"
    BUG_DETECT = "bug_detection"
    REFACTOR = "refactor"


class Intent(BaseModel):
    type: Literal[
        "generate_code",
        "autocomplete",
        "explain_code",
        "bug_detection",
        "refactor"
    ]

class CodeGenerationResult(BaseModel):

    code: str = Field(
        ...,
        description="Generated code that solves the user's task."
    )

    explanation: Optional[str] = Field(
        default=None,
        description="Short explanation of the generated code."
    )

class CodeExplanationResult(BaseModel):

    explanation: str = Field(
        ...,
        description="Detailed explanation of the provided code."
    )

    key_points: Optional[List[str]] = Field(
        default=None,
        description="Important concepts used in the code."
    )

class BugDetectionResult(BaseModel):

    bugs: List[str] = Field(
        ...,
        description="List of detected bugs or issues."
    )

    fixed_code: Optional[str] = Field(
        default=None,
        description="Corrected version of the code."
    )

    suggestions: Optional[List[str]] = Field(
        default=None,
        description="Additional improvements or best practices."
    )


class AutocompleteResult(BaseModel):

    completion: str = Field(
        ...,
        description="Only the newly generated continuation of the code that completes the snippet."
    )

    full_code: str = Field(
        ...,
        description="The complete code after applying the completion to the original snippet."
    )


class CodeAuditResult(BaseModel):
    vulnerabilities: Optional[List[str]] = Field(
        default=None,
        description="List of security or authentication issues detected in the code."
    )

    severity: Optional[List[str]] = Field(
        default=None,
        description="Severity corresponding to each detected vulnerability. Values: low, medium, high."
    )

    fixed_code: Optional[str] = Field(
        default=None,
        description="Optionally corrected or safer version of the code."
    )

    suggestions: Optional[List[str]] = Field(
        default=None,
        description="Additional recommendations to improve security or code safety."
    )

class AgentState(BaseModel):

    user_input: str = Field(
        ...,
        description="The raw prompt provided by the user."
    )

    intent: Optional[IntentType] = Field(
        default=None,
        description="Detected intent of the user request (e.g., generate code, explain code)."
    )

    messages: List[Message] = Field(
        default_factory=list,
        description="Conversation history between the user and the assistant."
    )

    code_context: CodeContext = Field(
        default_factory=CodeContext,
        description="Structured information about the code extracted from the prompt."
    )

    retrieval_context: RetrievalContext = Field(
        default_factory=RetrievalContext,
        description="Context retrieved from project files or vector database to assist the LLM."
    )

    result: Optional[str] = Field(
        default=None,
        description="Final response generated by the assistant after task execution."
    )

    last_code: Optional[str] = Field(
        default=None,
        description="Last generated or processed code snippet used for follow-up operations."
    )

    task: Optional[str] = None

    # New field to store audit results
    audit_context: Optional[CodeAuditResult] = Field(
        default=None,
        description="Structured information about code vulnerabilities detected by the audit node."
    )

    # Optional: keep a history of audit outputs for reference
    audit_history: Optional[List[CodeAuditResult]] = Field(
        default_factory=list,
        description="List of previous audit results for tracking multiple scans."
    )



class CodeRefinementResult(BaseModel):
    refined_code: str = Field(
        ...,
        description="The updated code with added docstrings and comments."
    )
    changes: Optional[List[str]] = Field(
        default=None,
        description="List of changes applied, e.g., 'Added docstring to function X', 'Added comment to loop'."
    )